import clsx from 'clsx';
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useEmployeeDetailQuery } from '../features/employees/useEmployeeQueries';

const getInitials = (name) => name.split(' ').filter(Boolean).map((part) => part[0]).slice(0, 2).join('').toUpperCase();
const Field = ({ label, value }) => <div><p className="text-sm text-slate-400 mb-2">{label}</p><div className="bg-slate-800/60 border border-slate-700/50 rounded-lg px-3 py-2 text-white">{value}</div></div>;

export const EmployeeDetailPage = () => {
  const { id } = useParams(); const navigate = useNavigate(); const [activeTab, setActiveTab] = useState('work');
  const { data: employee, isLoading, isError } = useEmployeeDetailQuery(id);
  if (isLoading) return <div className="p-8 max-w-7xl mx-auto text-slate-400">Loading employee...</div>;
  if (isError || !employee) return <div className="p-8 max-w-7xl mx-auto text-rose-400">Unable to load employee.</div>;
  const smartButtons = [['Time Off', employee.timeOffCount, '/time-off'], ['Contracts', employee.contractsCount, '/contracts'], ['Attendance', employee.attendanceCount, '/attendance']];
  return <div className="p-8 max-w-7xl mx-auto space-y-8"><div><h1 className="text-3xl font-extrabold text-white tracking-tight">Employee / {employee.name}</h1><p className="text-slate-400 mt-1">Main employee form with related HR actions</p></div><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><button type="button" className="border border-slate-700 text-slate-300 rounded-lg px-4 py-2 text-sm font-medium hover:bg-slate-800">Edit</button><div className="flex flex-wrap gap-3">{smartButtons.map(([label, count, path]) => <button key={label} type="button" onClick={() => navigate(`${path}?employeeId=${employee.id}`)} className="border border-brand-500/40 text-brand-400 rounded-lg px-4 py-2 text-sm font-medium hover:bg-brand-500/10">{label} {count}</button>)}</div></div><section className="rounded-2xl bg-slate-800/60 border border-slate-700/50 backdrop-blur shadow-xl p-6"><div className="flex items-center gap-4"><div className="w-14 h-14 shrink-0 rounded-xl bg-brand-500/10 border border-brand-500/30 flex items-center justify-center text-brand-500 font-bold">{getInitials(employee.name)}</div><div><h2 className="text-xl font-semibold text-white">{employee.name}</h2><p className="text-slate-400 mt-1">{employee.role} • {employee.department}</p><p className="text-slate-500 text-sm mt-1">{employee.email} | {employee.phone}</p></div></div><div className="flex gap-6 border-b border-slate-700/50 mt-8"><button type="button" onClick={() => setActiveTab('work')} className={clsx('pb-3 text-sm font-medium border-b-2', activeTab === 'work' ? 'border-brand-500 text-brand-500' : 'border-transparent text-slate-400')}>Work Information</button><button type="button" onClick={() => setActiveTab('private')} className={clsx('pb-3 text-sm font-medium border-b-2', activeTab === 'private' ? 'border-brand-500 text-brand-500' : 'border-transparent text-slate-400')}>Private Information</button></div>{activeTab === 'work' && <div className="grid grid-cols-2 gap-x-8 gap-y-5 mt-6"><div className="space-y-5"><Field label="Department" value={employee.department} /><Field label="Manager" value={employee.manager} /><Field label="Working Schedule" value={employee.workingSchedule} /><Field label="Company" value={employee.company} /></div><div className="space-y-5"><Field label="Job Position" value={employee.jobPosition} /><Field label="Work Location" value={employee.workLocation} /><Field label="Status" value={employee.status} /><Field label="Work Email" value={employee.workEmail} /></div></div>}{activeTab === 'private' && <div className="min-h-24 mt-6" />}</section><p className="text-xs text-slate-500 pt-2">Useful note: smart buttons should open related Contracts, Attendance and Time Off records filtered for the current employee.</p></div>;
};
