version: '3.8'

services:
  hr-service:
    volumes:
      - ../services/hr-service/app:/app/app
      - ../shared/python-libs/common:/app/shared/common

  attendance-timeoff-service:
    volumes:
      - ../services/attendance-timeoff-service/app:/app/app
      - ../shared/python-libs/common:/app/shared/common

  payroll-service:
    volumes:
      - ../services/payroll-service/app:/app/app
      - ../shared/python-libs/common:/app/shared/common

  api-gateway:
    volumes:
      - ../services/api-gateway/app:/app/app
      - ../shared/python-libs/common:/app/shared/common

  frontend:
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
